[project]
name = "pyrizon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dask>=2024.10.0",
    "mysql-connector-repackaged>=0.3.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "scikit-learn>=1.5.2",
]
